reward_model:
  enable: true

  # Whether to deploy th emodle to a separate resource pool
  enable_resource_pool: true
  n_gpus_per_node: ${trainer.n_gpus_per_node}
  nnodes: 1

  # Model configuration
  model:
    type: huggingface
    path: meta-llama/Llama-3.1-8B-Instruct
    trust_remote_code: false
  
  # Rollout
  rollout:
    name: sglang
    dtype: ${actor_rollout_ref.rollout.dtype}
    gpu_memory_utilization: ${actor_rollout_ref.rollout.gpu_memory_utilization}
    enforce_eager: true
    cudagraph_capture_sizes: null
    free_cache_engine: true
    data_parallel_size: 1
    tensor_model_parallel_size: 2
    expert_parallel_size: 1
    max_num_batched_tokens: 8192
    max_model_len: null
    max_num_seqs: 1024
    load_format: auto
    engine_kwargs: {}
    limit_images: null
    enable_chunked_prefill: true
    enable_prefix_caching: true
    disable_log_stats: true
    skip_tokenizer_init: true
    launch_reward_fn_async: true
    prompt_length: ${data.max_prompt_length}
    response_length: 512
