defaults:
  - ppo_trainer
  - _self_

data:
  max_prompt_length: 2048
  max_response_length: 2048
  trust_remote_code: ${trust_remote_code}
  train_batch_size: 16
  val_batch_size: 16
  truncation: left
  train_files:
    - ./mock_dataset/mock_dataset.parquet
  val_files:
    - ./mock_dataset/mock_dataset.parquet

trainer:
  nnodes: 1
  n_gpus_per_node: 4
  project_name: verl-test
  experiment_name: v01
  logger: [console]

critic:
  enable: false
  model:
    trust_remote_code: ${trust_remote_code}

algorithm:
  adv_estimator: grpo
  use_kl_in_reward: false
  kl_ctrl:
    kl_coef: 0.0
  filter_groups:
    enable: true
    metric: acc
    max_num_gen_batches: 0 # Non-positive integer mean no upper limit

reward_model:
  enable: false
  model:
    trust_remote_code: ${trust_remote_code}
  # Which reward manager to use. Currently supported values: 'batch', 'naive', 'prime', 'dapo', 'async_dapo'
  reward_manager: naive
  overlong_buffer: 
    enable: False # We try to avoid forgetting to set enable
    len: 0
    penalty_factor: 0.0
    log: False

actor_rollout_ref:
  model:
    path: meta-llama/Llama-3.1-8B-Instruct
    use_shm: false
    use_remove_padding: false
    enable_gradient_checkpointing: false
    trust_remote_code: ${trust_remote_code}
  rollout:
    prompt_length: ${data.max_prompt_length}
    response_length: ${data.max_response_length}
    max_model_len: null
    max_num_batched_tokens: 8192
    max_num_seqs: 512
    n: 32
    load_format: auto
    dtype: bfloat16
    name: sglang

    log_prob_micro_batch_size_per_gpu: 16
    tensor_model_parallel_size: ${trainer.n_gpus_per_node}
    data_parallel_size: ${trainer.nnodes}
    gpu_memory_utilization: 0.6
    free_cache_engine: false

    temperature: 0.8
    top_p: 1.0
    top_k: 50
  actor:
    entropy_checkpointing: true
    fsdp_config:
      model_dtype: bfloat16
      param_offload: false
      optimizer_offload: false
      offload_policy: false
      strategy: fsdp2

    optim:
      lr: 1e-6

    ppo_micro_batch_size_per_gpu: 4
    ppo_mini_batch_size: 128
    
    use_kl_loss: true
    kl_loss_coef: 0.001
    kl_loss_type: low_var_kl
    entropy_coeff: 0
  ref:
    log_prob_micro_batch_size_per_gpu: ${actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu}
    fsdp_config:
      model_dtype: bfloat16
      param_offload: ${actor_rollout_ref.actor.fsdp_config.param_offload}
      optimizer_offload: ${actor_rollout_ref.actor.fsdp_config.optimizer_offload}
      offload_policy: ${actor_rollout_ref.actor.fsdp_config.offload_policy}
      strategy: ${actor_rollout_ref.actor.fsdp_config.strategy}

global_profiler:
  enable: false
  tool: null

ray:
  dashboard: 0.0.0.0:8265
  # num_cpus: 16
  num_cpus: null # Do not set when running the server

  timeline_json_file: null

# Global setting for trusting remote code when loading models
trust_remote_code: false

# Turn on experimental verl features
verl_experimental: false
