hydra:
  searchpath:
    - pkg://multimeditron.config
    - pkg://verl.trainer.config

defaults:
  - verl_trainer
  - nsjail-python-exec-pool
  - model/llama-3.1-70b
  - _self_

data:
  max_prompt_length: 2048
  max_response_length: 2048
  return_raw_chat: true
  train_files:
    - /capstor/store/cscs/swissai/a127/meditron/multimediset/reasoning/math-shepherd.parquet
  val_files:
    - /capstor/store/cscs/swissai/a127/meditron/multimediset/reasoning/math-shepherd-val.parquet
  prompt_key: prompt
  reward_fn_key: data_source
  return_multi_modal_inputs: false

actor_rollout_ref:
  model:
    path: ${model.path}
    tokenizer_path: ${oc.select:model.tokenizer_path,null}
  rollout:
    # max_num_batched_tokens: 16384
    n: 64
    # max_num_seqs: 256
    multi_turn:
      enable: true
      max_tool_response_length: 2048
      max_assistant_turns: 3
      tokenization_sanity_check_mode: strict
      tool_config_path: /users/gboye/MultiMeditron/config/rl/grpo/tools.yaml
